//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF6DatabaseFirstUsingEDMX.DAL.EDMX
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingMember
    {
        public int MeetingId { get; set; }
        public int MemberId { get; set; }
        public bool IsAttending { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual Meeting Meeting { get; set; }
        public virtual Member Member { get; set; }
    }
}
